### ISSUE TITLE
afl-dyninst: Segmentation fault when instrumenting Position Independent Executable 

### ISSUE THREAD

**Issue by dzamlo** [vrtadmin/moflow#5]
If you try to instrument an Position Independent Executable (code compiled with the "-fPIC -pie" options for exemple), afl-dyninst segfault.

Here is what I found:
On [line 250](https://github.com/vrtadmin/moflow/blob/40637c9b3448afaf3bf5b5ba3c7cfb09b8f84c85/afl-dyninst/afl-dyninst.cpp#L250), defaultModule is declared.
On [line 265](https://github.com/vrtadmin/moflow/blob/40637c9b3448afaf3bf5b5ba3c7cfb09b8f84c85/afl-dyninst/afl-dyninst.cpp#L265) defaultModule get its value. But this line is only executed if there is a module named `DEFAULT_MODULE`. If the executable is a PIE, dyninst doesn't produce a module named `DEFAULT_MODULE`.
Then, [line 289](https://github.com/vrtadmin/moflow/blob/40637c9b3448afaf3bf5b5ba3c7cfb09b8f84c85/afl-dyninst/afl-dyninst.cpp#L289) is executed. But because line 265 is never executed, defaultModule is still equal to NULL.

**Comment by richinseattle** [comment]
Hi Loic,

Thanks for the bug report. We have merged a patch from Aleks, can you
please test this out and confirm it fixes your issue?

Cheers,
Rich

**Comment by Vogtinator** [comment]
I ran into the same issue today, so it's not completely fixed.

**Comment by richinseattle** [comment]
Can you share the binary causing this issue or more information?

**Comment by Vogtinator** [comment]
It's a binary using Qt 5.5.1, which requires that -fPIC is used.
I added some debug statements and there is no DEFAULT_MODULE,
I had to hardcode default_module_name to be "crtstuff.c", as it contains _init.
That works, but when adding a Qt module with the "-r" option, it prints out

```
SERIOUS #109: That function does not exist
```

and quits.

[dyninstcrash.zip](https://github.com/vrtadmin/moflow/files/67449/dyninstcrash.zip)

**Comment by richinseattle** [comment]
Thanks for the report, I'm about to release a docker with our tools and
will try to get this patched up before the release.

Cheers,
Rich

**Comment by ea** [comment]
@Vogtinator 

Hi ,

although I can reproduce the issue with no DEFAULT_MODULE (that part of the code isn't generic enough, I know) I can't reproduce the segfault after hardcoding the "crtstuff.c" as DEFAULT_MODULE. 

Which version of Dyninst are you using? 

I'll make a fix for the first issue soon.

**Comment by Vogtinator** [comment]
> I can't reproduce the segfault after hardcoding the "crtstuff.c" as DEFAULT_MODULE.

It happens during modification of the .so, without the .so it works fine.

> Which version of Dyninst are you using?

The latest from git as of 6 days ago.

**Comment by ea** [comment]
Yes, understood that part. 

I'll try to repro with their latest git version, maybe it's a regression.

Thanks!

**Comment by ea** [comment]
Indeed there seems to be some regression with 64bit -fPIC -pie binaries in dyninst.
Simply rewriting the binary, without adding any code/instrumentation breaks ELF sections 
and causes a crash. Will report to devs and see what to do.
